project_id      = "moa-prod2"
region          = "asia-northeast3"
zone            = "asia-northeast3-c"
environment     = "prod"
frontend_domain = "moagenda.com"
backend_domain  = "backend.moagenda.com"
credentials_file = "path_to_credential"