# values.yaml BE 기준

replicaCount: 2

image:
  repository: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

env:
  - name: ENV
    value: "production"

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: moa-backend.<your-domain>.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - moa-backend.<your-domain>.com
      secretName: moa-tls-cert